[highlight]
codeFences = false

[goldmark.renderer]
unsafe = true

[goldmark.extensions.passthrough]
enable = true

[goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"]]
