baseURL = "https://lets-remember.github.io/"
languageCode = "en-us"
title = "Let's Remember"

defaultContentLanguage = "en"

[module]
[[module.imports]]
# path = "github.com/yihui/hugo-xmin"
# path = "github.com/clente/hugo-bearcub"
# path = 'github.com/spf13/hyde'
# path = 'github.com/hanwenguo/hugo-theme-nostyleplease'
# path = "github.com/nunocoracao/blowfish"
path = "github.com/tomfran/typo"

[permalinks]
posts = "/:year/:month/:title/"
