baseURL = "https://lets-remember.github.io/"
languageCode = "en-us"
title = "Let's Remember"

defaultContentLanguage = "en"

[module]
[[module.imports]]
path = "github.com/yihui/hugo-xmin"
# path = "github.com/clente/hugo-bearcub"
# path = 'github.com/spf13/hyde'
# path = 'github.com/hanwenguo/hugo-theme-nostyleplease'
# path = "github.com/nunocoracao/blowfish"
# path = "github.com/tomfran/typo"

[permalinks]
posts = "/:year/:month/:title/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "RSS"
url = "index.xml"

[params]
description = "A website built through Hugo and blogdown."
footer = "Markdown Footer. Edit this and it is markdown. in the config.toml"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"]]
