baseURL = "https://lets-remember.github.io/"
languageCode = "en-us"
title = "Let's Remember"
theme = 'github.com/yihui/hugo-xmin'
defaultContentLanguage = "en"

[module]
[[module.imports]]
path = "github.com/yihui/hugo-xmin"

[permalinks]
posts = "/:year/:month/:title/"
